apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: python-script-
spec:
  entrypoint: run-python-script
  serviceAccountName: argo-events-ksa
  arguments:
    parameters:
      - name: sql_file_path
        value: "{{workflow.parameters.sql_file_path}}"

  templates:
    - name: run-python-script
      inputs:
        parameters:
          - name: sql_file_path
      container:
        image: us-central1-docker.pkg.dev/gke-expeiments/cme-setup/baseimage:latest
        command: [python3]
        args: ["/app/bq_transform.py", "{{inputs.parameters.sql_file_path}}"]
