apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    iam.gke.io/gcp-service-account: owner-gke-argo@gke-expeiments.iam.gserviceaccount.com
  name: argo-events-ksa
  namespace: argo
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: argo
  name: role-argo-events-ksa
rules:
  - apiGroups: ["argoproj.io"]
    resources: ["workflows"]
    verbs: ["get","list","watch","create","update","patch","delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: executor
rules:
  - apiGroups:
      - argoproj.io
    resources:
      - workflowtaskresults
    verbs:
      - create
      - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argo-basic-role
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - pods/exec
      - configmaps
      - services
      - persistentvolumeclaims
    verbs:
      - create
      - get
      - list
      - watch
      - update
      - patch
      - delete
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - create
      - get
      - list
      - update
      - patch
      - delete
  - apiGroups:
      - apps
    resources:
      - deployments
      - statefulsets
    verbs:
      - create
      - get
      - list
      - watch
      - update
      - patch
      - delete
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: role-argo-events-ksa-binding
  namespace: argo
subjects:
  - kind: ServiceAccount
    name: argo-events-ksa
    namespace: argo
roleRef:
  kind: Role
  name: role-argo-events-ksa
  apiGroup: rbac.authorization.k8s.io
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: role-argo-basic-ksa-pod-binding
  namespace: argo
subjects:
  - kind: ServiceAccount
    name: argo-events-ksa
    namespace: argo
roleRef:
  kind: Role
  name: argo-basic-role
  apiGroup: rbac.authorization.k8s.io
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: role-argo-executor-ksa-binding
  namespace: argo
subjects:
  - kind: ServiceAccount
    name: argo-events-ksa
    namespace: argo
roleRef:
  kind: Role
  name: executor
  apiGroup: rbac.authorization.k8s.io
#---
#kind: RoleBinding
#apiVersion: rbac.authorization.k8s.io/v1
#metadata:
# name: role-argo-cluster-ksa-binding
# namespace: argo
#subjects:
#- kind: ServiceAccount
#  name: argo-events-ksa
#  namespace: argo
#roleRef:
# kind: Role
# name: argo-cluster-role
# apiGroup: rbac.authorization.k8s.io
#---
#kind: RoleBinding
#apiVersion: rbac.authorization.k8s.io/v1
#metadata:
# name: role-argo-events-ksa-pod-binding
# namespace: argo
#subjects:
#- kind: ServiceAccount
#  name: argo-events-ksa
#  namespace: argo
#roleRef:
# kind: Role
# name: argo-events-role
# apiGroup: rbac.authorization.k8s.io
#---