apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: gcp-pubsub
spec:
  template:
    serviceAccountName: argo-events-ksa
    container:
      resources:
        requests:
          cpu: "15m"
          memory: "150Mi"
        limits:
          cpu: "25m"
          memory: "250Mi"
  dependencies:
    - name: test-dep
      eventSourceName: gcp-pubsub
      eventName: example
  triggers:
    - template:
        name: gcp-workflow
        k8s:
          operation: create
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: gcp-workflow-
              spec:
                entrypoint: whalesay
                arguments:
                  parameters:
                    - name: message
                      # value will get overridden by the event payload
                      value: hello world
                templates:
                  - name: whalesay
                    inputs:
                      parameters:
                        - name: message
                    container:
                      image: us-central1-docker.pkg.dev/gke-expeiments/cme-setup/docker/whalesay:latest
                      resources:
                        requests:
                          cpu: "5m"
                          memory: "100Mi"
                        limits:
                          cpu: "10m"
                          memory: "200Mi"
                      command: [cowsay]
                      args: ["{{inputs.parameters.message}}"]
          parameters:
            - src:
                dependencyName: test-dep
                dataKey: body
              dest: spec.arguments.parameters.0.value