app:
  name: demo-api
  description: "Demo API for testing"
  debug: True
  port: 8080
  version: 0.05
  author: Deloitte
DEK: 
DEID_WRAPPED_KEY: CiQAyHYOXhnCOrF5mPdZMiRMXGCi72WrEBJdwk9qxLmQfOifPzUSSQBxGTtDrghgk/Pp1XsSAKRg6pezaJcMfi3iJV1451hUT32IE3KMHV7dkgZDtDv9lomXXaLfMuS3Dklh6pt+UuCJzZbWXp5cICo=
CRYPTO_KEY_NAME: projects/us-gcp-ame-con-ff12d-npd-1/locations/global/keyRings/keyring-dip/cryptoKeys/dlp-kms-key